### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by geotheory** [hoesler/rwantshue#1]
Hi.  I think your latest edits killed the function.  The default `palette` now returns this for me: 
`Error in palette(n = 8, force_mode = FALSE, quality = 50, color_space = hcl_presets$fancy_light,  : 
  unused arguments (n = 8, force_mode = FALSE, quality = 50, color_space = hcl_presets$fancy_light, js_color_mapper = I("function(color) { return color.hex(); }"))`

**Comment by hoesler** [comment]
Thanks for the feedback. I made a series of small commits and I think the bug should already be fixed.
My tests are succeeding here. Please try to update again.

Am 22.01.2015 um 15:46 schrieb Robin Edwards notifications@github.com:

**Comment by geotheory** [comment]
Nice work, I'll definitely use this!  If you want to make the customisation more explicit you could maybe add something like this to the documentation:
`scheme = iwanthue();
hcl_pars = list(c(330, 360), # hue range [0,360]
               c(0, 3),     # chroma range [0,3]
               c(0, 1.5));   # lightness range [0,1.5]
cols = scheme$hex(n = 8, force_mode = FALSE, quality = 50, color_space = hcl_pars);
pie(rep(1,length(cols)), col = cols, labels=NA)`

**Comment by geotheory** [comment]
Couldn't find you on Twitter but https://twitter.com/geotheory/status/558286095784607744

**Comment by hoesler** [comment]
Thanks!
Sure, I will update the readme.
My twitter id is hoesler, but I rarely use it.
